/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConditioningPackage;

import com.sun.jdi.request.BreakpointRequest;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.HashSet;



/**
 *
 * @author mjsh6
 */
public class SupplyScreen extends javax.swing.JFrame {

    /**
     * Creates new form SupplyScreen
     */
    String IPAddress;
    String settingsFilePath;
    String LogFolderPath;
    int port;
    DXM supply;
    Warmup_Handler warmup;
    boolean startRead = false;
    SettingsHandler sh;
    ConditioningHandler ch;
    String SerialNumber = "";
    AutoReadOutHandler AROH;
    
    
    
    public SupplyScreen(String IPAddress,String port,String SettingsFilePath, String LogFolderPath) {
        initComponents();
        this.IPAddress = IPAddress;
        if(SettingsFilePath != ""){
            this.sh = new SettingsHandler(SettingsFilePath);
            Load_Settings();}
        this.LogFolderPath = LogFolderPath;
        this.port = Integer.valueOf(port);
        this.supply = new DXM(this.IPAddress,this.port);
        this.update_UI();
        this.warmup = new Warmup_Handler(this.supply, this.WarmupSelectionButtonGroup, this.WarmUpProgressBar,
                this.WarmVoltageTBox,this.WarmCurrentTBox,this.FillCurrTBox,this.PreHeatTBox);
        this.AROH = new AutoReadOutHandler(this.supply, this.VoltageReadoutLabel, 
                this.CurrentReadoutLabel, this.ConditionVoltageReadTBox, 
                this.ConditionCurrentReadTBox, this.ConditionFillamentReadTBox);
    }
    
    public SupplyScreen(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WarmupSelectionButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ManualControlPanel = new javax.swing.JPanel();
        XrayOnOffPanel = new javax.swing.JPanel();
        XrayOnButton = new javax.swing.JButton();
        XrayOffButton = new javax.swing.JButton();
        VoltageLabel = new javax.swing.JLabel();
        CurrentLabel = new javax.swing.JLabel();
        VoltageSetTBox = new javax.swing.JTextField();
        CurrentSetTBox = new javax.swing.JTextField();
        kvLabel = new javax.swing.JLabel();
        maLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        VoltageReadoutLabel = new javax.swing.JLabel();
        CurrentReadoutLabel = new javax.swing.JLabel();
        SupplySettingsPanel = new javax.swing.JPanel();
        SupplyWattageTBox = new javax.swing.JTextField();
        SupplyWattageLabel = new javax.swing.JLabel();
        SupplyMaxKVTbox = new javax.swing.JTextField();
        SupplyMaxKVLabel = new javax.swing.JLabel();
        SupplyMaxMaLabel = new javax.swing.JLabel();
        SupplyMaxMATBox = new javax.swing.JTextField();
        WarmupPanel = new javax.swing.JPanel();
        WarmupTitleLabel = new javax.swing.JLabel();
        RadioButton7min = new javax.swing.JRadioButton();
        RadioButton15min = new javax.swing.JRadioButton();
        StartWarmupButton = new javax.swing.JButton();
        StopWarmupButton = new javax.swing.JButton();
        WarmUpProgressBar = new javax.swing.JProgressBar();
        WarmKVLabel = new javax.swing.JLabel();
        WarmVoltageTBox = new javax.swing.JTextField();
        WarmMALabel = new javax.swing.JLabel();
        WarmCurrentTBox = new javax.swing.JTextField();
        ReconnectToSupplyButton = new javax.swing.JButton();
        TubeSerialNumberTBox = new javax.swing.JTextField();
        TubeSerialNumberLabel = new javax.swing.JLabel();
        TubeConditioningPanel = new javax.swing.JPanel();
        ConditioningSettingsPanel = new javax.swing.JPanel();
        StartingMALabel = new javax.swing.JLabel();
        StartingMATBox = new javax.swing.JTextField();
        TotalStepCountTBox = new javax.swing.JTextField();
        TimeBetweenStepsTBox = new javax.swing.JTextField();
        TotalStepCountLabel = new javax.swing.JLabel();
        TimeBetweenStepsLabel = new javax.swing.JLabel();
        StartingKVTBox = new javax.swing.JTextField();
        StartingKVLabel = new javax.swing.JLabel();
        TargetKVTBox = new javax.swing.JTextField();
        TargetKVLabel = new javax.swing.JLabel();
        OnOffCycleTimeOnLabel = new javax.swing.JLabel();
        NumberOfOnOffCyclesTBox = new javax.swing.JTextField();
        TargetMATBox = new javax.swing.JTextField();
        TargetMALabel = new javax.swing.JLabel();
        OnOffCycleTimeOffTBox = new javax.swing.JTextField();
        OnOffCycleTimeOffLabel = new javax.swing.JLabel();
        NumberOfOnOffCyclesLabel = new javax.swing.JLabel();
        OnOffCycleTimeOnTBox = new javax.swing.JTextField();
        TotalArcsBeforeStopLabel = new javax.swing.JLabel();
        TotalArcsBeforeStopTBox = new javax.swing.JTextField();
        ArcMAStepTBox = new javax.swing.JTextField();
        ArcKVStepTBox = new javax.swing.JTextField();
        ArcKVStepLabel = new javax.swing.JLabel();
        ArcMAStepLabel = new javax.swing.JLabel();
        ArcRecoveryTimeTBox = new javax.swing.JTextField();
        ArcRecoveryTimeLabel = new javax.swing.JLabel();
        PreHeatLabel = new javax.swing.JLabel();
        PreHeatTBox = new javax.swing.JTextField();
        FilCurrLabel = new javax.swing.JLabel();
        FillCurrTBox = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        LaodDefaultButton = new javax.swing.JButton();
        ConditioningControlPanel = new javax.swing.JPanel();
        StartConditioningButton = new javax.swing.JButton();
        StopConditioningButton = new javax.swing.JButton();
        ConditioningProgressBar = new javax.swing.JProgressBar();
        ProgressBarLabel = new javax.swing.JLabel();
        TimeRemainingLabel = new javax.swing.JLabel();
        ConditionVoltageReadTBox = new javax.swing.JTextField();
        ConditionVoltageReadLabel = new javax.swing.JLabel();
        ConditionCurrentReadTBox = new javax.swing.JTextField();
        ConditionCurrentReadLabel = new javax.swing.JLabel();
        ConditionFillamentReadTBox = new javax.swing.JTextField();
        ConditionFillamentReadLabl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supply Screen");

        XrayOnOffPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        XrayOnButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        XrayOnButton.setText("XRAY ON");
        XrayOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XrayOnButtonActionPerformed(evt);
            }
        });

        XrayOffButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        XrayOffButton.setText("XRAY OFF");
        XrayOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XrayOffButtonActionPerformed(evt);
            }
        });

        VoltageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VoltageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoltageLabel.setText("VOLTAGE(kV)");

        CurrentLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CurrentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentLabel.setText("CURRENT(mA)");

        VoltageSetTBox.setText("0.0");

        CurrentSetTBox.setText("0.0");
        CurrentSetTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentSetTBoxActionPerformed(evt);
            }
        });

        kvLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kvLabel.setText("kV");

        maLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maLabel.setText("mA");

        TitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Manual Xray Control");

        VoltageReadoutLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        VoltageReadoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoltageReadoutLabel.setText("0.0");

        CurrentReadoutLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        CurrentReadoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentReadoutLabel.setText("0.0");

        javax.swing.GroupLayout XrayOnOffPanelLayout = new javax.swing.GroupLayout(XrayOnOffPanel);
        XrayOnOffPanel.setLayout(XrayOnOffPanelLayout);
        XrayOnOffPanelLayout.setHorizontalGroup(
            XrayOnOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XrayOnOffPanelLayout.createSequentialGroup()
                .addGroup(XrayOnOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(XrayOnOffPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VoltageReadoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentReadoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(XrayOnOffPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(XrayOnOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(XrayOnOffPanelLayout.createSequentialGroup()
                                .addGroup(XrayOnOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(XrayOnOffPanelLayout.createSequentialGroup()
                                        .addComponent(kvLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(VoltageSetTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(maLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CurrentSetTBox))
                                    .addGroup(XrayOnOffPanelLayout.createSequentialGroup()
                                        .addComponent(XrayOnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(XrayOffButton, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(XrayOnOffPanelLayout.createSequentialGroup()
                                .addComponent(VoltageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CurrentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))))
                .addContainerGap())
        );

        XrayOnOffPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {XrayOffButton, XrayOnButton});

        XrayOnOffPanelLayout.setVerticalGroup(
            XrayOnOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XrayOnOffPanelLayout.createSequentialGroup()
                .addComponent(TitleLabel)
                .addGap(18, 18, 18)
                .addGroup(XrayOnOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltageLabel)
                    .addComponent(CurrentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(XrayOnOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentReadoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VoltageReadoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(XrayOnOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XrayOnButton)
                    .addComponent(XrayOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(XrayOnOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltageSetTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentSetTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kvLabel)
                    .addComponent(maLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        XrayOnOffPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {XrayOffButton, XrayOnButton});

        SupplySettingsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SupplyWattageTBox.setEditable(false);
        SupplyWattageTBox.setText("0.0");

        SupplyWattageLabel.setText("Supply Wattage:");

        SupplyMaxKVTbox.setEditable(false);
        SupplyMaxKVTbox.setText("0.0");

        SupplyMaxKVLabel.setText("Supply Max kV:");

        SupplyMaxMaLabel.setText("Supply Max mA:");

        SupplyMaxMATBox.setEditable(false);
        SupplyMaxMATBox.setText("0.0");

        javax.swing.GroupLayout SupplySettingsPanelLayout = new javax.swing.GroupLayout(SupplySettingsPanel);
        SupplySettingsPanel.setLayout(SupplySettingsPanelLayout);
        SupplySettingsPanelLayout.setHorizontalGroup(
            SupplySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SupplySettingsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SupplySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SupplyMaxKVLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SupplyWattageLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SupplyMaxMaLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(SupplySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SupplyWattageTBox, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(SupplyMaxKVTbox)
                    .addComponent(SupplyMaxMATBox))
                .addContainerGap())
        );
        SupplySettingsPanelLayout.setVerticalGroup(
            SupplySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplySettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SupplySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplyWattageTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplyWattageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SupplySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplyMaxKVTbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplyMaxKVLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SupplySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplyMaxMATBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplyMaxMaLabel))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        WarmupPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        WarmupTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WarmupTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WarmupTitleLabel.setText("Warm up");

        WarmupSelectionButtonGroup.add(RadioButton7min);
        RadioButton7min.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButton7min.setSelected(true);
        RadioButton7min.setText("7-min");

        WarmupSelectionButtonGroup.add(RadioButton15min);
        RadioButton15min.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButton15min.setText("15-min");

        StartWarmupButton.setText("Start Warmup");
        StartWarmupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartWarmupButtonActionPerformed(evt);
            }
        });

        StopWarmupButton.setText("Stop Warmup");
        StopWarmupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopWarmupButtonActionPerformed(evt);
            }
        });

        WarmKVLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WarmKVLabel.setText("kV");

        WarmVoltageTBox.setText("0.0");

        WarmMALabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WarmMALabel.setText("mA");

        WarmCurrentTBox.setText("0.0");
        WarmCurrentTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarmCurrentTBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WarmupPanelLayout = new javax.swing.GroupLayout(WarmupPanel);
        WarmupPanel.setLayout(WarmupPanelLayout);
        WarmupPanelLayout.setHorizontalGroup(
            WarmupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WarmupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WarmupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WarmupTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WarmUpProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(WarmupPanelLayout.createSequentialGroup()
                        .addComponent(StartWarmupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StopWarmupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WarmupPanelLayout.createSequentialGroup()
                        .addGroup(WarmupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WarmupPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(RadioButton7min, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                            .addGroup(WarmupPanelLayout.createSequentialGroup()
                                .addComponent(WarmKVLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WarmVoltageTBox)))
                        .addGap(18, 18, 18)
                        .addGroup(WarmupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(WarmupPanelLayout.createSequentialGroup()
                                .addComponent(RadioButton15min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(14, 14, 14))
                            .addGroup(WarmupPanelLayout.createSequentialGroup()
                                .addComponent(WarmMALabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WarmCurrentTBox)))))
                .addContainerGap())
        );

        WarmupPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {RadioButton15min, RadioButton7min});

        WarmupPanelLayout.setVerticalGroup(
            WarmupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WarmupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WarmupTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WarmupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButton7min)
                    .addComponent(RadioButton15min))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WarmupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WarmVoltageTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WarmCurrentTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WarmKVLabel)
                    .addComponent(WarmMALabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(WarmupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartWarmupButton)
                    .addComponent(StopWarmupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WarmUpProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        WarmupPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {StartWarmupButton, StopWarmupButton});

        ReconnectToSupplyButton.setText("Reconnect To Supply");
        ReconnectToSupplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReconnectToSupplyButtonActionPerformed(evt);
            }
        });

        TubeSerialNumberTBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TubeSerialNumberTBoxMouseClicked(evt);
            }
        });
        TubeSerialNumberTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TubeSerialNumberTBoxActionPerformed(evt);
            }
        });

        TubeSerialNumberLabel.setText("Enter Tube Number:");

        javax.swing.GroupLayout ManualControlPanelLayout = new javax.swing.GroupLayout(ManualControlPanel);
        ManualControlPanel.setLayout(ManualControlPanelLayout);
        ManualControlPanelLayout.setHorizontalGroup(
            ManualControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualControlPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ManualControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManualControlPanelLayout.createSequentialGroup()
                        .addGroup(ManualControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(XrayOnOffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReconnectToSupplyButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ManualControlPanelLayout.createSequentialGroup()
                        .addComponent(TubeSerialNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TubeSerialNumberTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(ManualControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SupplySettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WarmupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        ManualControlPanelLayout.setVerticalGroup(
            ManualControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualControlPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ManualControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManualControlPanelLayout.createSequentialGroup()
                        .addComponent(SupplySettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WarmupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ManualControlPanelLayout.createSequentialGroup()
                        .addComponent(XrayOnOffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReconnectToSupplyButton)
                        .addGap(35, 35, 35)
                        .addGroup(ManualControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TubeSerialNumberTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TubeSerialNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manual Control", ManualControlPanel);

        ConditioningSettingsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StartingMALabel.setText("Starting mA:");

        StartingMATBox.setText("0.0");

        TotalStepCountTBox.setText("0.0");

        TimeBetweenStepsTBox.setText("0.0");

        TotalStepCountLabel.setText("Total Step Count:");

        TimeBetweenStepsLabel.setText("Time Between Steps(min):");

        StartingKVTBox.setText("0.0");

        StartingKVLabel.setText("Starting kV:");

        TargetKVTBox.setText("0.0");

        TargetKVLabel.setText("Target kV:");

        OnOffCycleTimeOnLabel.setText("On/Off Cycle Time On(min):");

        NumberOfOnOffCyclesTBox.setText("0.0");

        TargetMATBox.setText("0.0");

        TargetMALabel.setText("Target mA:");

        OnOffCycleTimeOffTBox.setText("0.0");

        OnOffCycleTimeOffLabel.setText("On/Off Cycle Time Off(min):");

        NumberOfOnOffCyclesLabel.setText("Number of On /Off Cycles:");

        OnOffCycleTimeOnTBox.setText("0.0");

        TotalArcsBeforeStopLabel.setText("Total Arcs Before Stop:");

        TotalArcsBeforeStopTBox.setText("0.0");

        ArcMAStepTBox.setText("0.0");

        ArcKVStepTBox.setText("0.0");

        ArcKVStepLabel.setText("Arc kv Step:");

        ArcMAStepLabel.setText("Arc mA Step:");

        ArcRecoveryTimeTBox.setText("0.0");

        ArcRecoveryTimeLabel.setText("Arc Recovery Time(min):");

        PreHeatLabel.setText("Filament Pre-heat: ");

        PreHeatTBox.setText("0.0");

        FilCurrLabel.setText("Filament Current Limit: ");

        FillCurrTBox.setText("0.0");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        LaodDefaultButton.setText("Load Default");
        LaodDefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaodDefaultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConditioningSettingsPanelLayout = new javax.swing.GroupLayout(ConditioningSettingsPanel);
        ConditioningSettingsPanel.setLayout(ConditioningSettingsPanelLayout);
        ConditioningSettingsPanelLayout.setHorizontalGroup(
            ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConditioningSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NumberOfOnOffCyclesLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(OnOffCycleTimeOffLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(OnOffCycleTimeOnLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(TargetMALabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StartingMALabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TargetKVLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StartingKVLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TimeBetweenStepsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TotalStepCountLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConditioningSettingsPanelLayout.createSequentialGroup()
                        .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StartingMATBox)
                            .addComponent(TargetKVTBox)
                            .addComponent(StartingKVTBox)
                            .addComponent(TimeBetweenStepsTBox)
                            .addComponent(TotalStepCountTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ConditioningSettingsPanelLayout.createSequentialGroup()
                                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ArcMAStepLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ArcRecoveryTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TotalArcsBeforeStopLabel)
                                        .addComponent(ArcKVStepLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ArcRecoveryTimeTBox)
                                    .addComponent(ArcMAStepTBox)
                                    .addComponent(ArcKVStepTBox)
                                    .addComponent(TotalArcsBeforeStopTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ConditioningSettingsPanelLayout.createSequentialGroup()
                                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FilCurrLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PreHeatLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PreHeatTBox)
                                    .addComponent(FillCurrTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ConditioningSettingsPanelLayout.createSequentialGroup()
                        .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OnOffCycleTimeOffTBox)
                            .addComponent(OnOffCycleTimeOnTBox)
                            .addComponent(NumberOfOnOffCyclesTBox)
                            .addComponent(TargetMATBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaveButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LaodDefaultButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        ConditioningSettingsPanelLayout.setVerticalGroup(
            ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConditioningSettingsPanelLayout.createSequentialGroup()
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalStepCountTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalStepCountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeBetweenStepsTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeBetweenStepsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartingKVTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartingKVLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TargetKVTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TargetKVLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartingMATBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartingMALabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TargetMATBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TargetMALabel))
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfOnOffCyclesTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberOfOnOffCyclesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OnOffCycleTimeOnTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OnOffCycleTimeOnLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OnOffCycleTimeOffTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OnOffCycleTimeOffLabel))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConditioningSettingsPanelLayout.createSequentialGroup()
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalArcsBeforeStopTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalArcsBeforeStopLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArcKVStepTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArcKVStepLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArcMAStepTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArcMAStepLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArcRecoveryTimeTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArcRecoveryTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FillCurrTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FilCurrLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConditioningSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreHeatTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreHeatLabel))
                .addGap(9, 9, 9)
                .addComponent(SaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LaodDefaultButton)
                .addContainerGap())
        );

        ConditioningControlPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StartConditioningButton.setText("Start Conditioning");
        StartConditioningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartConditioningButtonActionPerformed(evt);
            }
        });

        StopConditioningButton.setText("Stop Conditioning");
        StopConditioningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopConditioningButtonActionPerformed(evt);
            }
        });

        ProgressBarLabel.setText("Progress:");

        TimeRemainingLabel.setText("0.0 min");

        ConditionVoltageReadTBox.setEditable(false);
        ConditionVoltageReadTBox.setText("0.0");

        ConditionVoltageReadLabel.setText("Read Voltage:");

        ConditionCurrentReadTBox.setEditable(false);
        ConditionCurrentReadTBox.setText("0.0");

        ConditionCurrentReadLabel.setText("Read Current:");

        ConditionFillamentReadTBox.setEditable(false);
        ConditionFillamentReadTBox.setText("0.0");

        ConditionFillamentReadLabl.setText("Read Fillament Current:");

        javax.swing.GroupLayout ConditioningControlPanelLayout = new javax.swing.GroupLayout(ConditioningControlPanel);
        ConditioningControlPanel.setLayout(ConditioningControlPanelLayout);
        ConditioningControlPanelLayout.setHorizontalGroup(
            ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConditioningControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConditioningControlPanelLayout.createSequentialGroup()
                        .addComponent(ProgressBarLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConditioningProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TimeRemainingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addGroup(ConditioningControlPanelLayout.createSequentialGroup()
                        .addComponent(StartConditioningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StopConditioningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConditionFillamentReadLabl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ConditionVoltageReadLabel)
                                .addComponent(ConditionCurrentReadLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ConditionFillamentReadTBox)
                            .addComponent(ConditionCurrentReadTBox)
                            .addComponent(ConditionVoltageReadTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        ConditioningControlPanelLayout.setVerticalGroup(
            ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConditioningControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimeRemainingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConditioningProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProgressBarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConditioningControlPanelLayout.createSequentialGroup()
                        .addGap(18, 20, Short.MAX_VALUE)
                        .addGroup(ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StopConditioningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StartConditioningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(ConditioningControlPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConditionVoltageReadTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConditionVoltageReadLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConditionCurrentReadTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConditionCurrentReadLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ConditioningControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConditionFillamentReadTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConditionFillamentReadLabl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout TubeConditioningPanelLayout = new javax.swing.GroupLayout(TubeConditioningPanel);
        TubeConditioningPanel.setLayout(TubeConditioningPanelLayout);
        TubeConditioningPanelLayout.setHorizontalGroup(
            TubeConditioningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TubeConditioningPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TubeConditioningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConditioningSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConditioningControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        TubeConditioningPanelLayout.setVerticalGroup(
            TubeConditioningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TubeConditioningPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConditioningSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ConditioningControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tube Conditioning", TubeConditioningPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CurrentSetTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentSetTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentSetTBoxActionPerformed
    
    public void update_UI(){
        switch (this.supply.modelNumber) {
                case "X4087":
                    this.SupplyMaxKVTbox.setText("40.0");
                    this.SupplyMaxMATBox.setText("30.0");
                    this.SupplyWattageTBox.setText("1200W");
                      
                    break;
                case "X3481":
                    this.SupplyMaxKVTbox.setText("30.0");
                    this.SupplyMaxMATBox.setText("10.0");
                    this.SupplyWattageTBox.setText("300W");
                    break;
                case "X4911":
                    this.SupplyMaxKVTbox.setText("40.0");
                    this.SupplyMaxMATBox.setText("15.0");
                    this.SupplyWattageTBox.setText("600W");
                    break;
                case "X4313":
                    this.SupplyMaxKVTbox.setText("30.0");
                    this.SupplyMaxMATBox.setText("20.0");
                    this.SupplyWattageTBox.setText("600W");
                    break;
                default:
                    this.SupplyMaxKVTbox.setText("0.0");
                    this.SupplyMaxMATBox.setText("0.0");
                    this.SupplyWattageTBox.setText("0W");
                    break;
                     
    }
    }
    private void XrayOnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XrayOnButtonActionPerformed
        Double voltage = Double.valueOf(this.VoltageSetTBox.getText());
        Double current = Double.valueOf(this.CurrentSetTBox.getText());
        this.supply.Set_Filament_Limit(Double.valueOf(this.FillCurrTBox.getText()));
        this.supply.Set_Filament_Preheat(Double.valueOf(this.PreHeatTBox.getText()));
        
        if(this.supply.Is_Emmitting()){
            this.supply.Set_Voltage(voltage);
            this.supply.Set_Current(current);
        }else{
            this.supply.Set_Voltage(voltage);
            this.supply.Set_Current(current);
            this.supply.Xray_On();
        }
        if (!AROH.isAlive()){
            this.AROH.Start_Auto_Readout();
        }
    }//GEN-LAST:event_XrayOnButtonActionPerformed

    private void XrayOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XrayOffButtonActionPerformed
        if(this.supply.Is_Emmitting()){
            this.supply.Xray_Off();
        }
        if (AROH.isAlive()){
            this.AROH.Stop_Auto_Readout();
        }
    }//GEN-LAST:event_XrayOffButtonActionPerformed

    private void StopWarmupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopWarmupButtonActionPerformed
        this.warmup.Stop_Warmup();
        if(!this.warmup.isAlive()){
            this.StartWarmupButton.setEnabled(true);    
        }
        this.warmup = new Warmup_Handler(this.supply, this.WarmupSelectionButtonGroup, this.WarmUpProgressBar,
                this.WarmVoltageTBox,this.WarmCurrentTBox,this.FillCurrTBox,this.PreHeatTBox);
        if (AROH.isAlive()){
            this.AROH.Stop_Auto_Readout();
        }
    }//GEN-LAST:event_StopWarmupButtonActionPerformed

    private void StartWarmupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartWarmupButtonActionPerformed
        this.StartWarmupButton.setEnabled(false);
        this.RadioButton7min.setActionCommand("7");
        this.RadioButton15min.setActionCommand("15");
        this.warmup.Start_Warmup();
        if (!AROH.isAlive()){
            this.AROH.Start_Auto_Readout();
        }
    }//GEN-LAST:event_StartWarmupButtonActionPerformed

    private void WarmCurrentTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarmCurrentTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WarmCurrentTBoxActionPerformed

    private void ReconnectToSupplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReconnectToSupplyButtonActionPerformed
        this.supply = new DXM(this.IPAddress,this.port);
        this.update_UI();
    }//GEN-LAST:event_ReconnectToSupplyButtonActionPerformed

    private void StopConditioningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopConditioningButtonActionPerformed
        if(ch.isAlive()){
            ch.Stop_Conditioning();
        }
        if (AROH.isAlive()){
            this.AROH.Stop_Auto_Readout();
        }
    }//GEN-LAST:event_StopConditioningButtonActionPerformed

    private void StartConditioningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartConditioningButtonActionPerformed
        ch = new ConditioningHandler(sh.appsettings, supply,this.ConditioningProgressBar);
        ch.Start_Conditioning();
        if (!AROH.isAlive()){
            this.AROH.Start_Auto_Readout();
        }
        
    }//GEN-LAST:event_StartConditioningButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        sh.appsettings.FilamentCurrentLimit = this.FillCurrTBox.getText();
        sh.appsettings.FilamentPreHeat = this.PreHeatTBox.getText();
        sh.appsettings.WarmupKV = this.WarmVoltageTBox.getText();
        sh.appsettings.WarmupMA = this.WarmCurrentTBox.getText();
        sh.appsettings.TotalStepCount = this.TotalStepCountTBox.getText();
        sh.appsettings.TimeBetweenSteps = this.TimeBetweenStepsTBox.getText();
        sh.appsettings.StartingKV = this.StartingKVTBox.getText();
        sh.appsettings.StartingMA = this.StartingMATBox.getText();
        sh.appsettings.TargetKV = this.TargetKVTBox.getText();
        sh.appsettings.TargetMA = this.TargetMATBox.getText();
        sh.appsettings.NumberOnOffCycles = this.NumberOfOnOffCyclesTBox.getText();
        sh.appsettings.OnCycleTime = this.OnOffCycleTimeOnTBox.getText();
        sh.appsettings.OffCycleTime = this.OnOffCycleTimeOffTBox.getText();
        sh.appsettings.TotalArcsBeforeStop = this.TotalArcsBeforeStopTBox.getText();
        sh.appsettings.ArcMAStep = this.ArcMAStepTBox.getText();
        sh.appsettings.ArcKVStep = this.ArcKVStepTBox.getText();
        sh.appsettings.ArcRecoveryTime = this.ArcRecoveryTimeTBox.getText();
        this.sh.SaveSettings();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void LaodDefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaodDefaultButtonActionPerformed
        this.sh.Reset_To_Default();
        
        this.Load_Settings();
    }//GEN-LAST:event_LaodDefaultButtonActionPerformed

    private void TubeSerialNumberTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TubeSerialNumberTBoxActionPerformed
        this.SerialNumber = this.TubeSerialNumberTBox.getText();
        System.out.println(this.SerialNumber);
        this.TubeSerialNumberTBox.setBackground(Color.lightGray);
        
    }//GEN-LAST:event_TubeSerialNumberTBoxActionPerformed

    private void TubeSerialNumberTBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TubeSerialNumberTBoxMouseClicked
        this.TubeSerialNumberTBox.setBackground(Color.white);
    }//GEN-LAST:event_TubeSerialNumberTBoxMouseClicked
    
    private void Load_Settings(){
        this.FillCurrTBox.setText(sh.appsettings.FilamentCurrentLimit);
        this.PreHeatTBox.setText(sh.appsettings.FilamentPreHeat);
        this.WarmVoltageTBox.setText(sh.appsettings.WarmupKV);
        this.WarmCurrentTBox.setText(sh.appsettings.WarmupMA);
        this.TotalStepCountTBox.setText(sh.appsettings.TotalStepCount);
        this.TimeBetweenStepsTBox.setText(sh.appsettings.TimeBetweenSteps);
        this.StartingKVTBox.setText(sh.appsettings.StartingKV);
        this.StartingMATBox.setText(sh.appsettings.StartingMA);
        this.TargetKVTBox.setText(sh.appsettings.TargetKV);
        this.TargetMATBox.setText(sh.appsettings.TargetMA);
        this.NumberOfOnOffCyclesTBox.setText(sh.appsettings.NumberOnOffCycles);
        this.OnOffCycleTimeOnTBox.setText(sh.appsettings.OnCycleTime);
        this.OnOffCycleTimeOffTBox.setText(sh.appsettings.OffCycleTime);
        this.TotalArcsBeforeStopTBox.setText(sh.appsettings.TotalArcsBeforeStop);
        this.ArcMAStepTBox.setText(sh.appsettings.ArcMAStep);
        this.ArcKVStepTBox.setText(sh.appsettings.ArcKVStep);
        this.ArcRecoveryTimeTBox.setText(sh.appsettings.ArcRecoveryTime);
                
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplyScreen().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArcKVStepLabel;
    private javax.swing.JTextField ArcKVStepTBox;
    private javax.swing.JLabel ArcMAStepLabel;
    private javax.swing.JTextField ArcMAStepTBox;
    private javax.swing.JLabel ArcRecoveryTimeLabel;
    private javax.swing.JTextField ArcRecoveryTimeTBox;
    private javax.swing.JLabel ConditionCurrentReadLabel;
    private javax.swing.JTextField ConditionCurrentReadTBox;
    private javax.swing.JLabel ConditionFillamentReadLabl;
    private javax.swing.JTextField ConditionFillamentReadTBox;
    private javax.swing.JLabel ConditionVoltageReadLabel;
    private javax.swing.JTextField ConditionVoltageReadTBox;
    private javax.swing.JPanel ConditioningControlPanel;
    private javax.swing.JProgressBar ConditioningProgressBar;
    private javax.swing.JPanel ConditioningSettingsPanel;
    private javax.swing.JLabel CurrentLabel;
    private javax.swing.JLabel CurrentReadoutLabel;
    private javax.swing.JTextField CurrentSetTBox;
    private javax.swing.JLabel FilCurrLabel;
    private javax.swing.JTextField FillCurrTBox;
    private javax.swing.JButton LaodDefaultButton;
    private javax.swing.JPanel ManualControlPanel;
    private javax.swing.JLabel NumberOfOnOffCyclesLabel;
    private javax.swing.JTextField NumberOfOnOffCyclesTBox;
    private javax.swing.JLabel OnOffCycleTimeOffLabel;
    private javax.swing.JTextField OnOffCycleTimeOffTBox;
    private javax.swing.JLabel OnOffCycleTimeOnLabel;
    private javax.swing.JTextField OnOffCycleTimeOnTBox;
    private javax.swing.JLabel PreHeatLabel;
    private javax.swing.JTextField PreHeatTBox;
    private javax.swing.JLabel ProgressBarLabel;
    private javax.swing.JRadioButton RadioButton15min;
    private javax.swing.JRadioButton RadioButton7min;
    private javax.swing.JButton ReconnectToSupplyButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton StartConditioningButton;
    private javax.swing.JButton StartWarmupButton;
    private javax.swing.JLabel StartingKVLabel;
    private javax.swing.JTextField StartingKVTBox;
    private javax.swing.JLabel StartingMALabel;
    private javax.swing.JTextField StartingMATBox;
    private javax.swing.JButton StopConditioningButton;
    private javax.swing.JButton StopWarmupButton;
    private javax.swing.JLabel SupplyMaxKVLabel;
    private javax.swing.JTextField SupplyMaxKVTbox;
    private javax.swing.JTextField SupplyMaxMATBox;
    private javax.swing.JLabel SupplyMaxMaLabel;
    private javax.swing.JPanel SupplySettingsPanel;
    private javax.swing.JLabel SupplyWattageLabel;
    private javax.swing.JTextField SupplyWattageTBox;
    private javax.swing.JLabel TargetKVLabel;
    private javax.swing.JTextField TargetKVTBox;
    private javax.swing.JLabel TargetMALabel;
    private javax.swing.JTextField TargetMATBox;
    private javax.swing.JLabel TimeBetweenStepsLabel;
    private javax.swing.JTextField TimeBetweenStepsTBox;
    private javax.swing.JLabel TimeRemainingLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel TotalArcsBeforeStopLabel;
    private javax.swing.JTextField TotalArcsBeforeStopTBox;
    private javax.swing.JLabel TotalStepCountLabel;
    private javax.swing.JTextField TotalStepCountTBox;
    private javax.swing.JPanel TubeConditioningPanel;
    private javax.swing.JLabel TubeSerialNumberLabel;
    private javax.swing.JTextField TubeSerialNumberTBox;
    private javax.swing.JLabel VoltageLabel;
    private javax.swing.JLabel VoltageReadoutLabel;
    private javax.swing.JTextField VoltageSetTBox;
    private javax.swing.JTextField WarmCurrentTBox;
    private javax.swing.JLabel WarmKVLabel;
    private javax.swing.JLabel WarmMALabel;
    private javax.swing.JProgressBar WarmUpProgressBar;
    private javax.swing.JTextField WarmVoltageTBox;
    private javax.swing.JPanel WarmupPanel;
    private javax.swing.ButtonGroup WarmupSelectionButtonGroup;
    private javax.swing.JLabel WarmupTitleLabel;
    private javax.swing.JButton XrayOffButton;
    private javax.swing.JButton XrayOnButton;
    private javax.swing.JPanel XrayOnOffPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel kvLabel;
    private javax.swing.JLabel maLabel;
    // End of variables declaration//GEN-END:variables
}
